add. CUD statement build
dotnetcore/SmartSql pull request #162
Opened 2022-04-11 10:03 UTC by gmij

2022-04-11 11:30 UTC, Ahoo-Wang requested changes

2022-04-12 06:04 UTC, gmij reviewed
请审核。

2022-04-12 12:07 UTC, Ahoo-Wang commented
@gmij 拉取一下上游代码（重构了单元测试），然后运行单元测试。

2022-04-12 12:57 UTC, Ahoo-Wang requested changes

2022-04-12 12:57 UTC, Ahoo-Wang commented on src/SmartSql.DyRepository/Annotations/CacheAttribute.cs
> +        public CUDCacheAttribute(string id, string type):base(id, type)
`CUDCacheAttribute ` 为什么需要这个？作用是？

2022-04-12 12:57 UTC, Ahoo-Wang commented on src/SmartSql/CUD/DbSessionExtensions.cs
> +            //}
删除已无用的注释。

2022-04-12 12:57 UTC, Ahoo-Wang commented on src/SmartSql/CUD/DbSessionExtensions.cs
> +            //if (enablePropertyChangedTrack == true)
删除已无用的注释。

2022-04-12 12:57 UTC, Ahoo-Wang commented on src/SmartSql/CUD/DbSessionExtensions.cs
> +            //    }
删除已无用的注释。

2022-04-12 13:22 UTC, gmij commented on src/SmartSql.DyRepository/Annotations/CacheAttribute.cs
> +        public CUDCacheAttribute(string id, string type):base(id, type)
打上这个标记，CUD自带的6个方法，会刷新缓存。

2022-04-13 05:59 UTC, merged